package horas_extras;

import APP.Conexion;
import inicio.inicio;
import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;


import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Fabian
 */
public class horas_extras extends javax.swing.JFrame {

    private String textoBusqueda;
    List<String> legajos, nombres, apellidos = new ArrayList<>();
    private DefaultTableModel tableModel;
    ButtonGroup btnGr;

    /**
     * Creates new form horas_extras
     */
    public horas_extras() {
        initComponents();
        // Crea un modelo de fecha

        tableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                // Deshabilitar la edición de todas las celdas
                return false;
            }
        };

        tableModel.addColumn("Nombre");
        tableModel.addColumn("Apellido");
        tableModel.addColumn("Legajo");
        legajos = new ArrayList<>();
        nombres = new ArrayList<>();
        apellidos = new ArrayList<>();

        try {
            Connection con = Conexion.getConexion();
            PreparedStatement statement = con.prepareStatement("SELECT legajo,nombre,apellido FROM empleados ORDER BY nombre ASC, apellido ASC");
            ResultSet resultado = statement.executeQuery();
            while (resultado.next()) {
                String legajo = resultado.getString("legajo");
                String nombre = resultado.getString("nombre");
                String apellido = resultado.getString("apellido");

                Object[] fila = {nombre, apellido, legajo};
                tableModel.addRow(fila);
                legajos.add(legajo);
                nombres.add(nombre);
                apellidos.add(apellido);

            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        StringBuilder sb = new StringBuilder();
        for (String legajo : legajos) {
            sb.append(legajo).append("\n");
        }
        for (String nombre : nombres) {
            sb.append(nombre).append("\n");
        }
        for (String apellido : apellidos) {
            sb.append(apellido).append("\n");
        }

        jTable1.setModel(tableModel);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        ButtonGroup btnGr = new ButtonGroup();
     
        btnGr.add(rbnSi);
        btnGr.add(rbtNo);
        
        rbtNo.setSelected(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtFondo = new javax.swing.JLabel();
        txtId = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblLupa = new javax.swing.JLabel();
        txtBuscador = new javax.swing.JTextField();
        cbxCantidad = new javax.swing.JComboBox<>();
        txtFecha = new javax.swing.JTextField();
        cbxMotivo = new javax.swing.JComboBox<>();
        cbxFin = new javax.swing.JComboBox<>();
        rbnSi = new javax.swing.JRadioButton();
        rbtNo = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cbxInicio = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cbxValor = new javax.swing.JComboBox<>();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel6 = new javax.swing.JLabel();
        txtLegajo = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BATERIA-MATEO-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 230, 170));

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BATERIAS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 130, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mateo-logo-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 410, 130));

        txtFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/horas_e.png"))); // NOI18N
        jPanel1.add(txtFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 580, 680));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 0, 590, 670));

        txtId.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 18)); // NOI18N
        jLabel4.setText("Carga de horas Extras");
        txtId.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -10, 450, 38));

        jLabel5.setFont(new java.awt.Font("Rockwell Extra Bold", 2, 14)); // NOI18N
        jLabel5.setText("Cantidad de Horas:");
        txtId.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 362, -1, -1));

        jLabel7.setFont(new java.awt.Font("Rockwell Extra Bold", 2, 14)); // NOI18N
        jLabel7.setText("Fecha:");
        txtId.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 60, -1));

        jLabel8.setFont(new java.awt.Font("Rockwell Extra Bold", 2, 14)); // NOI18N
        jLabel8.setText("Motivo:");
        txtId.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 127, -1));

        jLabel9.setFont(new java.awt.Font("Rockwell Extra Bold", 2, 14)); // NOI18N
        jLabel9.setText("Hora de Inicio:");
        txtId.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jLabel10.setFont(new java.awt.Font("Rockwell Extra Bold", 2, 14)); // NOI18N
        jLabel10.setText("Hora de Fin:");
        txtId.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 156, -1));

        jLabel11.setFont(new java.awt.Font("Rockwell Extra Bold", 2, 14)); // NOI18N
        jLabel11.setText("Feriado/Domingo:");
        txtId.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 561, -1, -1));

        lblLupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa-removebg-preview (1).png"))); // NOI18N
        txtId.add(lblLupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 31, 31));

        txtBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscadorActionPerformed(evt);
            }
        });
        txtBuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscadorKeyReleased(evt);
            }
        });
        txtId.add(txtBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 214, 30));

        cbxCantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        txtId.add(cbxCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 362, 280, -1));

        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        txtId.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 90, 30));

        cbxMotivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "Motivo1", "Motivo2", "Motivo3", "Motivo4" }));
        cbxMotivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMotivoActionPerformed(evt);
            }
        });
        txtId.add(cbxMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 402, 280, -1));

        cbxFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "00.00", "01.00", "02.00", "03.00", "04.00", "05.00", "06.00", "07.00", "08.00", "09.00", "10.00", "11.00", "12.00", "13.00", "14.00", "15.00", "16.00", "17.00", "18.00", "19.00", "20.00", "21.00", "22.00", "23.00" }));
        cbxFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFinActionPerformed(evt);
            }
        });
        txtId.add(cbxFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 482, 280, -1));

        rbnSi.setText("SI");
        rbnSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnSiActionPerformed(evt);
            }
        });
        txtId.add(rbnSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, 86, -1));

        rbtNo.setText("NO");
        rbtNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNoActionPerformed(evt);
            }
        });
        txtId.add(rbtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 560, 83, 22));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        txtId.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 470, 118));

        cbxInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "00.00", "01.00", "02.00", "03.00", "04.00", "05.00", "06.00", "07.00", "08.00", "09.00", "10.00", "11.00", "12.00", "13.00", "14.00", "15.00", "16.00", "17.00", "18.00", "19.00", "20.00", "21.00", "22.00", "23.00" }));
        txtId.add(cbxInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 442, 280, -1));

        jLabel12.setFont(new java.awt.Font("Rockwell Extra Bold", 2, 14)); // NOI18N
        jLabel12.setText("Valor de la hora:");
        txtId.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 156, -1));

        cbxValor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "50", "100", "150", "200", "250", "300" }));
        cbxValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxValorActionPerformed(evt);
            }
        });
        txtId.add(cbxValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 522, 280, -1));

        jCalendar1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCalendar1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCalendar1PropertyChange(evt);
            }
        });
        txtId.add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 370, 136));

        jLabel6.setFont(new java.awt.Font("Rockwell Extra Bold", 2, 14)); // NOI18N
        jLabel6.setText("Legajo:");
        txtId.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 76, 24));
        txtId.add(txtLegajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 71, 31));

        btnCancelar.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        btnCancelar.setText("VOLVER");
        btnCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        txtId.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 599, 100, 60));

        btnLimpiar.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        txtId.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 599, 100, 60));

        btnGuardar.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        txtId.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 599, 90, 60));

        jSeparator1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txtId.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 310, 10));

        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 510, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnSiActionPerformed

    private void txtBuscadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorKeyReleased

        String filtro = txtBuscador.getText(); // Obtener el texto del campo de búsqueda

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        jTable1.setRowSorter(sorter);

        if (filtro.trim().length() == 0) {
            sorter.setRowFilter(null); // No se aplica ningún filtro si el campo está vacío
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + filtro)); // Aplicar filtro ignorando mayúsculas/minúsculas
        }

    }//GEN-LAST:event_txtBuscadorKeyReleased

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if (!Validar()) {
            return;
        }
        String nombre = txtBuscador.getText();
        int cantidad = Integer.parseInt((String) cbxCantidad.getSelectedItem());
        String fecha = txtFecha.getText();
        String motivo = (String) cbxMotivo.getSelectedItem();
        String horaInicio = (String) cbxInicio.getSelectedItem();
        String horaFinal = (String) cbxFin.getSelectedItem();
        int valor = Integer.parseInt((String) cbxValor.getSelectedItem());
        String legajo = txtLegajo.getText();
        String feriado;

        if (rbnSi.isSelected()) {
            feriado = "SI";
        } else if (rbtNo.isSelected()) {
            feriado = "NO";
        } else {
            feriado = "NO";
        }

        try {
            Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareStatement("INSERT INTO hora_extra (nombre_empleado,cantidad_hora,fecha,motivo,hora_inicio,hora_fin,valor,feriado_domingo,legajo) VALUES (?,?,?,?,?,?,?,?,?)");
            ps.setString(1, nombre);
            ps.setInt(2, cantidad);
            ps.setString(3, fecha);
            ps.setString(4, motivo);
            ps.setString(5, horaInicio);
            ps.setString(6, horaFinal);
            ps.setInt(7, valor);
            ps.setString(8, feriado);
            ps.setString(9, legajo);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro guardado");
            limpiar();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        inicio ir = new inicio();
        ir.setVisible(true);
        hide();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selectedRow = jTable1.getSelectedRow();
        String nombre = jTable1.getValueAt(selectedRow, 0).toString();
        String apellido = jTable1.getValueAt(selectedRow, 1).toString();
        String legajo = jTable1.getValueAt(selectedRow, 2).toString();

        // Asigna el nombre y apellido al campo txtBuscador
        txtBuscador.setText(nombre + " " + apellido);
        txtLegajo.setText(legajo);
    }//GEN-LAST:event_jTable1MouseClicked

    private void cbxMotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMotivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMotivoActionPerformed

    private void cbxFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxFinActionPerformed

    private void cbxValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxValorActionPerformed

    private void rbtNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtNoActionPerformed

    private void jCalendar1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCalendar1PropertyChange
        if (evt.getOldValue() != null) {
            SimpleDateFormat fecha = new SimpleDateFormat("dd/MM/yyyy");
            txtFecha.setText(fecha.format(jCalendar1.getCalendar().getTime()));
        }
    }//GEN-LAST:event_jCalendar1PropertyChange

    private void txtBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscadorActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void limpiar() {
        txtBuscador.setText("");
        txtLegajo.setText("");
        txtFecha.setText("");
        cbxCantidad.setSelectedItem("Seleccione:");
        cbxMotivo.setSelectedItem("Seleccione:");
        cbxInicio.setSelectedItem("Seleccione:");
        cbxFin.setSelectedItem("Seleccione:");
        cbxValor.setSelectedItem("Seleccione:");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new horas_extras().setVisible(true);
        });

    }

    private boolean Validar() {
        boolean camposCompletos = false;

        if (!camposCompletos) {
            try {
                if (!txtBuscador.getText().isEmpty()) {
                    if (cbxCantidad.getSelectedIndex() != 0) {
                        if (!txtFecha.getText().isEmpty()) {
                            if (cbxMotivo.getSelectedIndex() != 0) {
                                if (cbxInicio.getSelectedIndex() != 0) {
                                    if (cbxFin.getSelectedIndex() != 0) {
                                        if (cbxValor.getSelectedIndex() != 0) {
                                            camposCompletos = true;
                                        } else {
                                            JOptionPane.showMessageDialog(this, "Seleccione el valor por favor", "mensaje de informacion", JOptionPane.ERROR_MESSAGE);
                                        }
                                    } else {
                                        JOptionPane.showMessageDialog(this, "Seleccione la hora de fin por favor", "mensaje de informacion", JOptionPane.ERROR_MESSAGE);
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(this, "Seleccione la hora de inicio por favor", "mensaje de informacion", JOptionPane.ERROR_MESSAGE);
                                }
                            } else {
                                JOptionPane.showMessageDialog(this, "Seleccione el motivo por favor", "mensaje de informacion", JOptionPane.ERROR_MESSAGE);
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Escriba la fecha correspondiente por favor", "mensaje de informacion", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Seleccione la cantidad de horas por favor", "mensaje de informacion", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Escriba el nombre por favor", "mensaje de informacion", JOptionPane.ERROR_MESSAGE);
                }
            } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }

        return true;
    }

    public void completarNombreApellido(String filtro) {
        String consulta = "SELECT nombre, apellido FROM empleados WHERE ( nombre LIKE ? OR apellido LIKE ? ,legajo Like ?)";
        Connection con = Conexion.getConexion();
        try (PreparedStatement stmt = con.prepareStatement(consulta)) {
            stmt.setString(1, filtro + "%");
            stmt.setString(2, filtro + "%");

            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {

                String nombre = rs.getString("nombre");
                String apellido = rs.getString("apellido");

                String nombreCompleto = nombre + " " + apellido;

                // Completa el nombre y apellido en el TextField
                txtBuscador.setText(nombreCompleto);
            } else {
                // No se encontraron resultados, puedes mostrar un mensaje o limpiar el TextField
                txtBuscador.setText("");
            }

            rs.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cbxCantidad;
    private javax.swing.JComboBox<String> cbxFin;
    private javax.swing.JComboBox<String> cbxInicio;
    private javax.swing.JComboBox<String> cbxMotivo;
    private javax.swing.JComboBox<String> cbxValor;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblLupa;
    private javax.swing.JRadioButton rbnSi;
    private javax.swing.JRadioButton rbtNo;
    private javax.swing.JTextField txtBuscador;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JLabel txtFondo;
    private javax.swing.JPanel txtId;
    private javax.swing.JTextField txtLegajo;
    // End of variables declaration//GEN-END:variables

    private int parseInteger(Object selectedItem) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
